# Generated by Django 4.2.3 on 2023-07-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='texto',
            field=models.TextField(verbose_name='Opinion'),
        ),
    ]
