# Generated by Django 4.2.3 on 2023-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.IntegerField(default='00000000'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-1-1', verbose_name='Fecha_nacimiento'),
        ),
    ]
