# Generated by Django 4.2.3 on 2023-08-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_alter_empleos_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleos',
            name='direccion',
            field=models.CharField(default='No aclarado', max_length=50),
        ),
        migrations.AddField(
            model_name='empleos',
            name='localidad',
            field=models.CharField(default='No aclarado', max_length=50),
        ),
        migrations.AddField(
            model_name='empleos',
            name='modalidad',
            field=models.CharField(default='No aclarado', max_length=50),
        ),
        migrations.AddField(
            model_name='empleos',
            name='numero',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
