# Generated by Django 4.2.3 on 2023-08-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, default='empleos/empleo_def.png', null=True, upload_to='mensajes'),
        ),
    ]
